Init serverless (#63)
meotitda/DICTIONARY pull request #87
Opened 2022-10-21 19:05 UTC by mahns1201

- serverless 기본 설정
- readme / tsconfig / prettier / eslint 공통 설정은 이번 커밋에서 제외

2022-10-21 19:06 UTC, mahns1201 commented
package.lock.json 안 만드려고 부단한 노력을 하였는데, 혹시 설정 잘못된 거 있다면 알려주시면 수정하겠습니다 :)

2022-10-22 05:32 UTC, MoonSupport reviewed
아직 offline으로만 테스트 해보신거죠?

2022-10-22 05:32 UTC, MoonSupport commented on packages/dictionary-api/serverless.yml
> +  runtime: nodejs14.x
버전 14로 하신 이유가 있나요?

2022-10-22 05:32 UTC, MoonSupport commented on package.json
> +    "@serverless/dashboard-plugin": "^6.2.2",
서버리스 관련 의존성이 root `package.json` 에 들어가야 할 이유가 있나요?

2022-10-22 05:33 UTC, MoonSupport commented
> @MoonSupport
> package.lock.json 안 만드려고 부단한 노력을 하였는데, 혹시 설정 잘못된 거 있다면 알려주시면 수정하겠습니다 :)

이거 생기는 경우가 있나요?

2022-10-22 06:53 UTC, mahns1201 commented on packages/dictionary-api/serverless.yml
> +  runtime: nodejs14.x
로컬이 14였네요... 16으로 업데이트 하였습니다.

2022-10-22 06:54 UTC, mahns1201 commented on package.json
> +    "@serverless/dashboard-plugin": "^6.2.2",
의존성 문제 해결하였습니다 !

2022-10-22 06:55 UTC, MoonSupport commented on package.json
> +    "serverless-offline": "^11.1.3",
```suggestion
```

2022-10-22 06:56 UTC, MoonSupport requested changes

2022-10-22 06:56 UTC, MoonSupport commented on package.json
> +    "serverless-offline": "^11.1.3",
```suggestion
```

2022-10-22 06:57 UTC, MoonSupport approved these changes
LGTM

2022-10-22 06:57 UTC, merged